blank_issues_enabled: false
contact_links:
  - name: 🐞 Bug Report
    url: https://github.com/ArsiQQ/metrika-detector-policy/issues/new?template=bug_report.md
    about: Сообщите о проблеме в расширении
  - name: 🚀 Feature Request
    url: https://github.com/ArsiQQ/metrika-detector-policy/issues/new?template=feature_request.md
    about: Предложите новую функцию или улучшение

